### PR TITLE
Add methods in url module to parse and trim credentials

### LINKED ISSUE #366: Add function to extract username and password from credential embedded URL in url module
**Describe the problem/challenge you have**
[A description of the current challenge that you are experiencing.]
When handling a credential embedded URL in the form of `https://username:password@URL`, we want to parse the credential information like `username` and `password`, store them into a k8s secret. Also we want to get a URL that doesn't contain the credential so we can store it elsewhere.

**Describe the solution you'd like**
[A clear and concise description of what you want to happen. If applicable a visual representation of the UX (ex: new CLI argument name, or resulting yaml).]

Involve following methods in `url` module:
1. `extract_username`: takes in a URL string, returns the embedded username as a string. If there's no credential, return `""`.
2. `extract_password`: takes in a URL string, returns the embedded password as a string. If there's no credential, return `""`.
3. `trim_credentials`: takes in a URL string, returns the URL that removes the credentials.

**Anything else you would like to add:**
[Additional information that will assist in solving the issue.]

_(see also: thread in [#carvel](https://kubernetes.slack.com/archives/CH8KCCKA5/p1619026581416200))_

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

### PR DESCRIPTION
**Pull request by hanlins**
Signed-off-by: Hanlin Shi <shihanlin9@gmail.com>

Introduce three methods in `url` module:
1. `extract_username`: to extract username in URL.
2. `extract_password`: to extract password in URL.
3. `trim_credentials`: to remove credentials in URL.

Closes #366.

### CODE REVIEW

**Comment by pivotaljohn** [comment]
> /hold on the discussion of the url module interface in the issue.

i.e. _this_ discussion: https://kubernetes.slack.com/archives/CH8KCCKA5/p1619033548435100?thread_ts=1619026581.416200&cid=CH8KCCKA5

**Comment by pivotaljohn** [comment]
Thanks for the thorough start here, @hanlins.

I'm thinking about an API that would be generalized, compact, and intuitive.

Looking around for how others have solved this same need, I see a number of standard libraries using the technique of parsing a string into an object that is then interrogated for the desired part(s). For example: https://golang.org/pkg/net/url/#Parse

FWIW, there's prior art within `ytt` for introducing new value types into the system: https://github.com/vmware-tanzu/carvel-ytt/blob/bc8782e60d1089a4781060d36811fea5bbbb608b/pkg/workspace/library_module.go#L128

Thoughts?

**Review by pivotaljohn — CHANGES_REQUESTED** [review]
Marking the PR as "Request Changes" to clearly indicate we're having a design discussion, right now.

**Comment by hanlins** [comment]
Hi @pivotaljohn, thanks for your replies! So do you mean instead of adding new methods ad-hoc into the `url` module, we should introduce a `url` type instead?

**Comment by pivotaljohn** [comment]
> Hi @pivotaljohn, thanks for your replies! So do you mean instead of adding new methods ad-hoc into the `url` module, we should introduce a `url` type instead?

That is what I'm suggesting, yes. 👍🏼

... and I am intending this to be a discussion.

In the process I see something like this:

1. identify a want/need ✔️ 
1. think big picture about what new/extended capability we could add that would not only solve for this use case, but the class of needs, generally.
1. converge on a solution that results in the most resilient design:
    - keeps interface and implementation complexity to only what's essential
    - keeps the API compact and features as orthogonal as possible
1. run with it, collaborating on the lower-level design decisions along the way

So, I'm jumping into step 2, there. Bringing up an idea and trying to "show my work" by articulating a rationale for that approach.

At this point, there may be other ideas. _Anyone_ can chime in here. And we can bat around other thoughts.

**Comment by hanlins** [comment]
Hi @pivotaljohn, this seems interesting, it seems to introduce a module-local type instead of a base type, is that correct? I think for a starting point, golang provides a nice implementation for URL already (https://github.com/golang/go/blob/e6ac2df2b198f583780277a7cf96e3b0b61fe0a1/src/net/url/url.go#L340-L369), maybe we parse a string to the golang URL and add methods to support existing use cases and add the new use cases we want to support.

**Comment by pivotaljohn** [comment]
> Hi @pivotaljohn, this seems interesting, it seems to introduce a module-local type instead of a base type, is that correct? I think for a starting point, golang provides a nice implementation for URL already (https://github.com/golang/go/blob/e6ac2df2b198f583780277a7cf96e3b0b61fe0a1/src/net/url/url.go#L340-L369), maybe we parse a string to the golang URL and add methods to support existing use cases and add the new use cases we want to support.

That sounds really enticing: less code for us to maintain (and make sure we get right). So long as the contract with Go's `url.URL` doesn't break, that should be just fine... right?


... another factor we need to keep in mind is ensuring that we maintain the sandbox.
`ytt` very consciously prevents any access to the outside world from within templates: no network, no disk, no time, no RNG, no encryption.

We do this for two reasons:
1. so that the tool is safe to use — sensitive data likely flows through here. Last think you need as an operator is for the deployment tool chain to exfiltrate secrets.
2. so that when the same inputs are given, the _exact_ same output is rendered — having this guarantee allows operators to gate potentially expensive operations so that they only execute if there was actually a change.

So, we'll want to make sure we don't inadvertently provide access to the outside world.

I'm not saying that I've spotted something like that yet, just putting it on your radar.

**Comment by pivotaljohn** [comment]
Are there any other viable (and meaningfully different) approaches we should consider?

**Comment by hanlins** [comment]
Hi @pivotaljohn, I'm trying to wrap these ideas in my mind so correct me if I'm wrong, I'm trying to understand the https://github.com/vmware-tanzu/carvel-ytt/blob/bc8782e60d1089a4781060d36811fea5bbbb608b/pkg/workspace/library_module.go#L128 example you used above.
So, what we've been talking about is to introduce a new type namely `urlValue` in the `url` module. In the `url` module, we can have a method namely `parse` to parse the URL, and what it returns is a starlark value, which is of `Module` type. And we still need to selectively expose the methods that this object, is that correct?

**Comment by hanlins** [comment]
Hi @pivotaljohn, I created https://github.com/vmware-tanzu/carvel-ytt/pull/372 which aggregates the methods into a `url` type, PTAL. If that is our direction then I'll close this one.

**Comment by hanlins** [comment]
Closing this changeset in favor of https://github.com/vmware-tanzu/carvel-ytt/pull/372.

**Pull request closed without merging**
