### PR TITLE
update test files: after "fix handling of unbalanced end and if/for/..." PR

### PR DESCRIPTION
**Pull request by phil9909**
Depends on https://github.com/k14s/starlark-go/pull/2

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@phil9909 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=k14s/ytt&pullRequestId=139)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=k14s/ytt&pullRequestId=139) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@phil9909 Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=k14s/ytt&pullRequestId=139)!

**Comment by cppforlife** [comment]
@phil9909 looks like you should be able to bump k14s/starlark-go.

**Comment by phil9909** [comment]
> @phil9909 looks like you should be able to bump k14s/starlark-go.

I'm on it

**Comment by phil9909** [comment]
Something went wrong with that rebase

**Pull request merged**
