### PR TITLE
Renamed file to match playground documentation

### LINKED ISSUE #541: Playground sample doc issue
**What steps did you take:**

Playground sample documentation error. 
**What happened:**

In the playground example "Getting-Started=>Externalize-Data-Value" the `_cmd_line.yaml` has incorrect file name in cmd `$ ytt -f config.yml -f values.yml`. File `values.yml` does not exist.

https://github.com/vmware-tanzu/carvel-ytt/blob/cdb721091345c9fcbab95d0df10608d6165b58af/examples/playground/getting-started/example-externalize-data-values/_cmd_line.yaml#L4
**What did you expect:**

The command should be `$ ytt -f config.yml -f schema.yml`

**Anything else you would like to add:**

**Environment:**

- ytt version (use `ytt --version`):0.36.0
- OS (e.g. from `/etc/os-release`):

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

### PR DESCRIPTION
**Pull request by rashedkvm**
Renamed file to match playground documentation

Closes #541 

Signed-off-by: Rashed Kamal <krashed@vmware.com>

### CODE REVIEW

**Review by cari-lynn — CHANGES_REQUESTED** [review]
Thank you @rashedkvm for helping find and improve the inconsistencies in the docs! 

We make a [distinction](https://carvel.dev/ytt/docs/latest/how-it-works/#data-values-schema-documents) between 'data _values_' files (files annotated with `@data/values`) and 'schema' files (files annotated with `@data/values-schema`). In this case, the file contains a `@data/values-schema` annotation, so we do want the file to be named `schema.yml`. Then in the example the line should say `schema.yml` instead of `values.yml`
https://github.com/vmware-tanzu/carvel-ytt/blob/cdb721091345c9fcbab95d0df10608d6165b58af/examples/playground/getting-started/example-externalize-data-values/_cmd_line.yaml#L4

**Comment by rashedkvm** [comment]
@cari-lynn makes sense. I will update the PR. Thanks!

**Comment by rashedkvm** [comment]
@cari-lynn updated PR, using `schema`. Thanks!

**Comment by cari-lynn** [comment]
Thank you! The change will be available once we redeploy the site

**Pull request merged**
