### PR TITLE
Replicate and fix #589

### LINKED ISSUE #589: Schema files are merged out-of-order when in different sub-directories
**What steps did you take:**
```console
$ tree .
.
├── add-schema.yml
└── config
    └── values
        └── schema.yml

2 directories, 2 files

$ cat config/values/schema.yml
#@data/values-schema
---
foo: 1

$ cat add-schema.yml
#@data/values-schema
---
#@overlay/match missing_ok=True
bar: 2

$ ytt -f config/ -f add-schema.yml
```

**What happened:**
```console
$ ytt -f config/ -f add-schema.yml
ytt: Error: Document on line values/schema.yml:2:
  Map item (key 'foo') on line values/schema.yml:3:
    Expected number of matched nodes to be 1, but was 0
```

**What did you expect:**
That they would be merged identically that they are for data values (i.e. respecting the order of the `-f` params).

**Anything else you would like to add:**
NOTE: This defect was fixed in 8e6cf37f327fd003df6cbdacc7ffd1c4f6bdd31c.

Placing the add-on schema file in the same path restores the expectation.

```console
$ ytt -f config/ -f add-schema.yml --file-mark=add-schema.yml:path=values/add-schema.yml --data-values-inspect
foo: 1
bar: 2
```

or

```console
$ mkdir -p custom/values
$ mv add-schema.yml custom/values/
$ ytt -f config/ -f add-schema.yml --data-values-inspect
foo: 1
bar: 2
```

**Environment:**

- ytt version (use `ytt --version`): 0.38.0

### PR DESCRIPTION
**Pull request by pivotaljohn**
Fixes #589

### CODE REVIEW

**Review by cari-lynn — APPROVED** [review]

**Comment by pivotaljohn** [comment]
Moving into draft: it's unclear whether we want this patch to land on v0.38.x or v0.37.x.

As soon as we figure that out, will pull out of draft.

**Comment by pivotaljohn** [comment]
Thanks for the review, @cari-lynn. 👍🏻

**Comment by pivotaljohn** [comment]
Upon reviewing LTS support matrix, this fix is only required for v0.37.x 👍🏻 

Will reposition...

**Comment by pivotaljohn** [comment]
Replayed as #613

**Pull request closed without merging**
