### PR TITLE
Add missing arg to regexp.replace example

### PR DESCRIPTION
**Pull request by reidmit**
I think this was a typo. Let me know (and feel free to close) if I'm misunderstanding something!

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@reid47 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=k14s/ytt&pullRequestId=200)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=k14s/ytt&pullRequestId=200) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@reid47 Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=k14s/ytt&pullRequestId=200)!

**Comment by mike1808** [comment]
🌝

**Comment by cppforlife** [comment]
yup, we just merged regexp.replace. will be available in the next release. thanks for catching typo.

**Pull request merged**
