### PR TITLE
enable to write `---` when starting doc

### PR DESCRIPTION
**Pull request by cappyzawa**
Usually, Yaml starts writing from `---`.

Is there a reason not to write `---` at the beginning of the output file?

<details>
<summary>I have been tested this chenges.</summary>

```
?   	github.com/k14s/ytt/cmd/lambda-playground	[no test files]
?   	github.com/k14s/ytt/cmd/ytt	[no test files]
?   	github.com/k14s/ytt/pkg/cmd	[no test files]
?   	github.com/k14s/ytt/pkg/cmd/core	[no test files]
=== RUN   TestLoad
--- PASS: TestLoad (0.00s)
=== RUN   TestDocumentOverlays
--- PASS: TestDocumentOverlays (0.00s)
=== RUN   TestBacktraceAcrossFiles
--- PASS: TestBacktraceAcrossFiles (0.00s)
=== RUN   TestDisallowDirectLibraryLoading
--- PASS: TestDisallowDirectLibraryLoading (0.00s)
=== RUN   TestRelativeLoadInLibraries
--- PASS: TestRelativeLoadInLibraries (0.00s)
PASS
ok  	github.com/k14s/ytt/pkg/cmd/template	0.110s
?   	github.com/k14s/ytt/pkg/filepos	[no test files]
?   	github.com/k14s/ytt/pkg/files	[no test files]
?   	github.com/k14s/ytt/pkg/playground	[no test files]
?   	github.com/k14s/ytt/pkg/structmeta	[no test files]
=== RUN   TestAncestorsDeep
--- PASS: TestAncestorsDeep (0.00s)
=== RUN   TestAncestorsSame
--- PASS: TestAncestorsSame (0.00s)
=== RUN   TestAncestorsShallow
--- PASS: TestAncestorsShallow (0.00s)
=== RUN   TestTemplatePlainStarlark
--- PASS: TestTemplatePlainStarlark (0.00s)
PASS
ok  	github.com/k14s/ytt/pkg/template	0.043s
?   	github.com/k14s/ytt/pkg/template/core	[no test files]
=== RUN   TestTextTemplate
checking code-after-code.txt ...
   .
checking code-with-comments.txt ...
   .
checking def-err-invalid.txt ...
   .
checking def.txt ...
   .
checking empty-code-block.txt ...
   .
checking empty.txt ...
   .
checking escape-err.txt ...
   .
checking escape.txt ...
   .
checking for.txt ...
   .
checking if.txt ...
   .
checking no-code.txt ...
   .
checking non-printing-code.txt ...
   .
checking printing-code.txt ...
   .
checking remove-space.yml ...
   .
checking unclosed-code.txt ...
   .
checking var-err-undefined.txt ...
   .
--- PASS: TestTextTemplate (0.01s)
PASS
ok  	github.com/k14s/ytt/pkg/texttemplate	0.065s
?   	github.com/k14s/ytt/pkg/workspace	[no test files]
=== RUN   TestParserDocSetEmpty
--- PASS: TestParserDocSetEmpty (0.00s)
=== RUN   TestParserDocSetNewline
--- PASS: TestParserDocSetNewline (0.00s)
=== RUN   TestParserOnlyComment
--- PASS: TestParserOnlyComment (0.00s)
=== RUN   TestParserDoc
--- PASS: TestParserDoc (0.00s)
=== RUN   TestParserDocWithoutDashes
--- PASS: TestParserDocWithoutDashes (0.00s)
=== RUN   TestParserRootValue
--- PASS: TestParserRootValue (0.00s)
=== RUN   TestParserRootString
--- PASS: TestParserRootString (0.00s)
=== RUN   TestParserMapArray
--- PASS: TestParserMapArray (0.00s)
=== RUN   TestParserMapComments
--- PASS: TestParserMapComments (0.00s)
=== RUN   TestParserArrayComments
--- PASS: TestParserArrayComments (0.00s)
=== RUN   TestParserDocSetComments
--- PASS: TestParserDocSetComments (0.00s)
=== RUN   TestParserDocSetOnlyComments2
--- PASS: TestParserDocSetOnlyComments2 (0.00s)
=== RUN   TestParserDocSetOnlyComments3
--- PASS: TestParserDocSetOnlyComments3 (0.00s)
=== RUN   TestParserDocSetOnlyComments
--- PASS: TestParserDocSetOnlyComments (0.00s)
=== RUN   TestParserDocSetCommentsNoFirstDashes
--- PASS: TestParserDocSetCommentsNoFirstDashes (0.00s)
=== RUN   TestParserUnindentedComment
--- PASS: TestParserUnindentedComment (0.00s)
=== RUN   TestParserInvalidDoc
--- PASS: TestParserInvalidDoc (0.00s)
PASS
ok  	github.com/k14s/ytt/pkg/yamlmeta	0.035s
=== RUN   TestYAMLTemplate
checking filetests/annotation.yml ...
   .
checking filetests/code-whitespace.yml ...
   .
checking filetests/comment.yml ...
   .
checking filetests/datatypes-err.yml ...
   .
checking filetests/datatypes.yml ...
   .
checking filetests/def-across-docs.yml ...
   .
checking filetests/def-doc.yml ...
   .
checking filetests/def-err-undefined.yml ...
   .
checking filetests/def-err-wrong-args.yml ...
   .
checking filetests/def-err-wrong-args2.yml ...
   .
checking filetests/def-recursive.yml ...
   .
checking filetests/def-return.yml ...
   .
checking filetests/def.yml ...
   .
checking filetests/for-break.yml ...
   .
checking filetests/for-continue.yml ...
   .
checking filetests/for.yml ...
   .
checking filetests/if-doc.yml ...
   .
checking filetests/if-elif-else.yml ...
   .
checking filetests/if-err-missing-colon.yml ...
   .
checking filetests/if-err-missing-end.yml ...
   .
checking filetests/if-inline.yml ...
   .
checking filetests/if-nested.yml ...
   .
checking filetests/if.yml ...
   .
checking filetests/map-key-override-err-with-def.yml ...
   .
checking filetests/map-key-override-err.yml ...
   .
checking filetests/map-key-override.yml ...
   .
checking filetests/node-sugar/node-elif.yml ...
   .
checking filetests/node-sugar/node-else.yml ...
   .
checking filetests/node-sugar/node-for-doc.yml ...
   .
checking filetests/node-sugar/node-for-nested.yml ...
   .
checking filetests/node-sugar/node-for.yml ...
   .
checking filetests/node-sugar/node-if-doc.yml ...
   .
checking filetests/node-sugar/node-if-err-nested.yml ...
   .
checking filetests/node-sugar/node-if-nested.yml ...
   .
checking filetests/node-sugar/node-if.yml ...
   .
checking filetests/pass.yml ...
   .
checking filetests/templated-string-err.yml ...
   .
checking filetests/templated-string.yml ...
   .
checking filetests/variable-err-undefined.yml ...
   .
checking filetests/variable.yml ...
   .
checking filetests/yaml-comment-indent.yml ...
   .
checking filetests/yaml-err.yml ...
   .
checking filetests/yaml-map-item-in-array-item.yml ...
   .
checking filetests/yaml-map-item-sorting.yml ...
   .
checking filetests/yaml-whitespace.yml ...
   .
checking filetests/ytt-library/base64.yml ...
   .
checking filetests/ytt-library/data-values.yml ...
   .
checking filetests/ytt-library/json.yml ...
   .
checking filetests/ytt-library/md5.yml ...
   .
checking filetests/ytt-library/overlay-doc-subset.yml ...
   .
checking filetests/ytt-library/overlay-inline-remove.yml ...
   .
checking filetests/ytt-library/overlay-insert-into-array.yml ...
   .
checking filetests/ytt-library/overlay-insert-into-doc.yml ...
   .
checking filetests/ytt-library/overlay-required-nested.yml ...
   .
checking filetests/ytt-library/overlay-subset.yml ...
   .
checking filetests/ytt-library/overlay-yaml-array-over-yaml-map.yml ...
   .
checking filetests/ytt-library/overlay-yaml-over-map.yml ...
   .
checking filetests/ytt-library/overlay.yml ...
   .
checking filetests/ytt-library/regexp.yml ...
   .
checking filetests/ytt-library/sha256.yml ...
   .
checking filetests/ytt-library/struct.yml ...
   .
checking filetests/ytt-library/yaml.yml ...
   .
checking filetests/ytt-replace/array-item.yml ...
   .
checking filetests/ytt-replace/doc-content-after.yml ...
   .
checking filetests/ytt-replace/doc-content-before.yml ...
   .
checking filetests/ytt-replace/doc-content-middle.yml ...
   .
checking filetests/ytt-replace/doc.yml ...
   .
checking filetests/ytt-replace/map-item.yml ...
   .
--- PASS: TestYAMLTemplate (0.09s)
PASS
ok  	github.com/k14s/ytt/pkg/yamltemplate	0.140s
?   	github.com/k14s/ytt/pkg/yttlibrary	[no test files]
?   	github.com/k14s/ytt/pkg/yttlibrary/overlay	[no test files]
UNIT SUCCESS
Version: 0.4.0
deleting: ../../tmp/config-alt1.yml
deleting: ../../tmp/config.yml
deleting: ../../tmp/eirini/config-alt1.yml
deleting: ../../tmp/eirini/config-alt2.yml
deleting: ../../tmp/eirini/config-result.yml
deleting: ../../tmp/eirini/config.yml
deleting: ../../tmp/eirini/data.txt
creating: ../../tmp/generated.go.txt
Version: 0.4.0
  adding: main (deflated 53%)
  adding: ytt (deflated 53%)
SUCCESS
creating: tmp/eirini/data.txt
creating: tmp/eirini/config-alt1.yml
creating: tmp/eirini/config-alt2.yml
creating: tmp/eirini/config-result.yml
creating: tmp/eirini/config.yml
E2E SUCCESS
ALL SUCCESS
```

</details>

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@cappyzawa Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=k14s/ytt&pullRequestId=10)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=k14s/ytt&pullRequestId=10) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@cappyzawa Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=k14s/ytt&pullRequestId=10)!

**Comment by cppforlife** [comment]
@cappyzawa hey, thank you for taking a look.

we currently do not add `---` when outputting files with a single document to keep output compact (tidy?). it abides by the yaml spec as shown in "9.1.3. Bare Documents" section: https://yaml.org/spec/1.2/spec.html#id2800967.

is there a particular reason why you would like to have an explicit document start marker?

**Comment by cappyzawa** [comment]
@cppforlife 
> is there a particular reason why you would like to have an explicit document start marker?

.... No. It is annoying that the warning of the linting tool (e.g. yamllint) if I must say. 
I didn't look yaml spec, I was thinking `---` is needed generally because the lint tool warns me in default setting...

Thanks for your description!
There is no problem if this follows yaml spec.

**Pull request closed without merging**
