### PR TITLE
Bumping go version to 1.19.6 in 0.43.x line

### PR DESCRIPTION
**Pull request by sethiyash**
- Bumping go version to 1.19.6 in 0.43.x line

### CODE REVIEW

**Comment by kencochrane** [comment]
1.19.7 is the latest version; should it be bumped to that one instead?

> go1.19.7 (released 2023-03-07) includes a security fix to the crypto/elliptic package, as well as bug fixes to the linker, the runtime, and the crypto/x509 and syscall packages. See the [Go 1.19.7 milestone](https://github.com/golang/go/issues?q=milestone%3AGo1.19.7+label%3ACherryPickApproved) on our issue tracker for details.

**Comment by rohitagg2020** [comment]
LGTM

**Comment by pivotaljohn** [comment]
> 1.19.7 is the latest version; should it be bumped to that one instead?
> 
> > go1.19.7 (released 2023-03-07) includes a security fix to the crypto/elliptic package, as well as bug fixes to the linker, the runtime, and the crypto/x509 and syscall packages. See the [Go 1.19.7 milestone](https://github.com/golang/go/issues?q=milestone%3AGo1.19.7+label%3ACherryPickApproved) on our issue tracker for details.

Hey @kencochrane. Thanks for calling that out. It's a legitimate question.

There's a number of concerns that get folded into selecting a specific dependency (even the version of Go we use). We have the desire to keep the suite in sync on Go version. It's currently some effort to produce new releases for all the tools and any downstream work that the VMware folks are also responsible for.

So, we'll pick a version and trigger a release.  Right now, sometimes that means not getting the absolute latest.

We're investing in our overall automation and making this effort shorter/cheaper. When we get to where we want to be, yeah, we'll be able to consume dependencies at will — as we'd all hope.

Again, thanks for the review; it's great to know folks are looking out, here. 👍🏻

**Comment by pivotaljohn** [comment]
It's my understanding that we are — whenever possible — making such changes on `develop` and then cherry-picking into version branches.

From what I'm seeing this change is not yet on `develop`.

Do I have my wires crossed? Or are we all still sync'ing up on this intended practice?

**Comment by sethiyash** [comment]
@pivotaljohn Thanks for pointing it out. I have missed checking on develop about the latest go version. 

I'm just closing this PR and raising a new PR to bump on develop first and cherry-picking into this branch.

**Comment by kencochrane** [comment]
@pivotaljohn Thank you for explaining that, and I totally get where you are coming from. I mainly brought it up because there are known [security issues](https://github.com/golang/go/issues/58647) with 1.19.6 that are fixed in 1.19.7, and I thought since it requires work to bump the version anyway, it might be a good idea to use a version of go with no known security vulnerabilities. 

When Go binaries are built with a version of Go that has known security vulnerabilities, it triggers security alerts on containers that contain those binaries. If companies want to stay in compliance, they have to fix those scan alerts within 30 to 90 days (depending on the CVE severity). Bumping to 1.19.7 would help those companies clear those alerts in their SLA window without needing another release.

It's your project, so feel free to do what is best. I just wanted to give a little heads-up in case it would have saved you time without having to do the whole process twice (with 1.19.6 and then again with 1.19.7).

Thanks again!

**Pull request closed without merging**
