### PR TITLE
chore: unnecessary use of fmt.Sprintf

### PR DESCRIPTION
**Pull request by testwill**

### CODE REVIEW

**Review by praveenrewar — APPROVED** [review]
Thank you ❤️

**Review by joaopapereira — APPROVED** [review]
Looks good

**Comment by vmunishwar** [comment]
Looks like copy paste error. Good catch :)

**Review by vmunishwar — APPROVED** [review]
Looks like copy paste error. Good catch :)

**Review by 100mik — APPROVED** [review]
lookin good!
Merging this away.

**Pull request merged**
