### PR TITLE
Improve load example with diferent data types

### PR DESCRIPTION
**Pull request by mildred**
Following issue #19, I improved the playground example to show various things:

- setting document values
- working with arrays as well as maps when defining functions using the document separator `---`
- working with scalars with starlark functions

I would have loved to demonstrate YAML indexing too but I couldn't, so I created issue #20

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@mildred Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=k14s/ytt&pullRequestId=21)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=k14s/ytt&pullRequestId=21) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@mildred Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=k14s/ytt&pullRequestId=21)!

**Comment by cppforlife** [comment]
@mildred should we add it here instead: https://github.com/k14s/ytt/tree/develop/examples/playground/example-function, since it's here that we introduce yaml fragments returned from functions?

**Comment by mildred** [comment]
Good idea, here is the updated version

**Pull request merged**
